### ISSUE TITLE
Refactor mesoscope pipeline to remove ROI separation step

### ISSUE THREAD

**Issue by kabilar** [datajoint-company/U19-pipeline_python#35]
- Mesoscope acquired data are separated into individual ROI TIFF files prior to running Suite2p, with the [insert_fov_mesoscope](https://github.com/BrainCOGS/U19-pipeline-matlab/blob/199c103e06c4eab73b165dd785871766d777999a/schemas/%2Bimaging/ScanInfo.m#L344) function.
- Need to determine if we can remove this step from the pipeline to eliminate the duplicated data, and simplify the [recording and imaging_pipeline schemas](https://github.com/BrainCOGS/U19-pipeline_python/blob/4abd9eb98cec1bc6140247bfed207a3ac9989eef/u19_pipeline/imaging_pipeline.py#L32-L112).

**Comment by kabilar** [comment]
ScanImage TIFF file readers:
- [scanreader](https://github.com/atlab/scanreader) 
- [tifffile](https://github.com/cgohlke/tifffile)
- [scanimage-tiff-reader](https://gitlab.com/vidriotech/scanimage-tiff-reader) - by ScanImage developers
- [Suite2p's loader](https://github.com/MouseLand/suite2p/blob/main/suite2p/io/tiff.py)
- ImageJ graphical interface

**Comment by kabilar** [comment]
I will send you a link to the data via Slack.  Not sure which datasets have the issue, but let's look into the headers to find a pattern.

**Comment by kabilar** [comment]
Hi @Alvalunasan, we are documenting our work with the mesoscope images in this issue.  Thanks.

**Comment by CBroz1** [comment]
Still waiting on server access, so I'm looking into header parsing. As a clarification question: under the current splitting process, where is the flag set for 'successfully split' vs. 'needs splitting'? By hand mismatch between header number of ROIs vs. resulting image shape?

**Comment by kabilar** [comment]
Thanks @CBroz1.  If I understood correctly, I think all images are currently split so that they can have the same folder and database structures for downstream processing.

**Comment by CBroz1** [comment]
> all images are currently split so that they can have the same folder and database structures for downstream processing

Before that split occurred, how were images flagged for splitting? Does metadata ingest correctly for these files?

**Comment by Alvalunasan** [comment]
Hi @CBroz1, I don't fully remember how this is done but I think images are always expected to measure 512 pixels wide
So, if I am right, basically all images are "split" but if they measure 512 pixels "only" they are not split in practice

From [insert_fov_mesoscope](https://github.com/BrainCOGS/U19-pipeline-matlab/blob/199c103e06c4eab73b165dd785871766d777999a/schemas/%2Bimaging/ScanInfo.m#L344)
`thisstack  = zeros(imheader{iF}(1).Height,512,numel(imheader{iF}),'uint16');`

**Comment by kabilar** [comment]
Action items after today's meeting with Mika
- Run Suite2p for `originalStacks` with parameters specifying a mesoscope image and compare against results for TIFF files containing a single ROI and single depth.
- Compare the following outputs from Suite2p:
    - *.bin file should contain a single ROI and depth
    - Metadata in `ops.npy`
    - Cell segmentations
    - Traces
    - Summary images
    - Compare timestamps from TIFF files and outputs from Suite2p
- Determine differences between ScanImage versions.
    - Required changes to the function that parses TIFF files ([insert_fov_mesoscope](https://github.com/BrainCOGS/U19-pipeline-matlab/blob/197202920002f42b971136d00fa6c5f2758c999b/schemas/%2Bimaging/ScanInfo.m#L344)).

**Comment by CBroz1** [comment]
I summarized my findings on [this issue](https://github.com/MouseLand/suite2p/issues/835) on Suite2p. We might be meeting with some of the Suit2p team next week and can touch on this issue there.

In short - the integrated Suite2p feature is not designed for our case. There's hope for it working out if I can revise [this Suite2p code](https://github.com/MouseLand/suite2p/blob/main/helpers/mesoscope_json_from_scanimage.m#L60-L63) with some of BrainCOGS team's code [here](https://github.com/BrainCOGS/mesoscopeImaging/blob/master/preproc/mesoscopeSetPreproc_multipleZs.m), but it would take some time

**Comment by CBroz1** [comment]
Using a [script provided by developers](https://drive.google.com/file/d/1yRMQ3ctf19SURQcoEE0u-qQj8s5uMA1T/view?usp=sharing), I tried generating parameters a couple different ways. I think Suite2p fundamentally assumes the same ROIs are captured at each Z-depth, which is not the case for our files. Perhaps, their [mesoscope to binary function](https://github.com/MouseLand/suite2p/blob/main/suite2p/io/tiff.py#L218) could be rewritten to accommodate, but this would be a major time sink. 

Meanwhile, we have [a script](https://github.com/BrainCOGS/mesoscopeImaging/blob/master/preproc/mesoscopeSetPreproc_multipleZs.m) that can readily split the files if passed an image folder. This could more readily be incorporated into an upstream table that split `Scan_Orig` into `Scan_Split` as input for `element-calcium-imaging`.

**Comment by Alvalunasan** [comment]
We settled on having SplitTiff with the original Matlab code.
Will close this issue
