### ISSUE TITLE
Transfer data after processing

### ISSUE THREAD

**Issue by kabilar** [datajoint-company/U19-pipeline_python#44]
- Add key to `ephys_element.PreClusterParamList.ParamOrder` table
- Key will specify which files to transfer from Tiger to the `/mnt/cup/braininit` drive.

**Comment by Alvalunasan** [comment]
Working on the new developments on this issue with PNIHelp and permission issues.

**Comment by kabilar** [comment]
I believe that this transfer has been resolved. Feel free to reopen if this is still pending.
