### ISSUE TITLE
Channel map creation

### ISSUE THREAD

**Issue by kabilar** [datajoint-company/U19-pipeline_python#54]
- [x] Neuropixels 1.0
- [x] Neuropixels 2.0
    - `element-array-ephys` stores electrodes for multi-shank probes sequentially.
    - Virtually mapping to physical electrodes does not correspond correctly with [write_channel_map_file](https://github.com/ttngu207/element-array-ephys/blob/85c7c8ba12154fff8695b1a66d9db96440e8bb08/element_array_ephys/readers/kilosort_triggering.py#L440-L478) and [get_recording_channels_details](https://github.com/ttngu207/element-array-ephys/blob/85c7c8ba12154fff8695b1a66d9db96440e8bb08/element_array_ephys/ephys_no_curation.py#L945-L979).  However, it is unclear how the kcoords variable is utilized in Kilosort.  See question https://github.com/MouseLand/Kilosort/issues/262.
    - Use [SGLXMetaToCoords](https://github.com/datajoint-company/ecephys_spike_sorting/blob/master/ecephys_spike_sorting/common/SGLXMetaToCoords.py) export function
    - Read raw data

**Comment by Alvalunasan** [comment]
Implemented [SGLXMetaToCoords](https://github.com/datajoint-company/ecephys_spike_sorting/blob/master/ecephys_spike_sorting/common/SGLXMetaToCoords.py) with the automation Pipeline.
The first tests of the channel map files seem to be working fine
